name: React CI

on: 
  push: 
    branches: 
      - "main"

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm build
      - run: npm test